name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Requirements
        run: pip install ".[dev]"

      - name: Test Code
        run: pytest -n auto --dist loadscope
